# 模板的名字，生成代码的根目录名称
name: admin-api
path: ${SYS['user.dir']}/../../
templates: mapper-templates
database:
  jdbcConnection:
    dialect: MYSQL
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moran?useSSL=false
    user: root
    password: xiyang
  # 获取表配置，支持 % 和 _ 模糊匹配，可以配置多个值
  # 还有一个支持复杂规则 tableRules 属性后续单独介绍
  tables:
    - 'sys_user'
    - 'sys_role'
    - 'sys_menu'
  typeMap:
    TINYINT: java.lang.Boolean
    VARCHAR: java.lang.String
    SMALLINT: java.lang.Integer
  typeTags:
    jdbcType:
      - DATE
      - TIME
      - TIMESTAMP
  keywordWrap: "`%s`"
  keywords:
    - order
    - desc
    - period
    - index
    - describe
attrs:
  basePackage: com.moran
files:
  - name: src/main
    files:
      - name: java
        files:
          - name: '${project.attrs.basePackage}'
            type: PACKAGE
            files:
              - name: mapper
                files:
                  - name: '${it.name.className}Mapper.java'
                    file: mapper.java
                    iter: tables
                    mode: ONCE
              - name: model
                files:
                  - name: '${it.name.className}.java'
                    # 此处有2种模板示例，分别列出来加了注释
                    #file: model.java
                    file: model-lombok.java
                    iter: tables
              - name: service
                files:
                  - name: '${it.name.className}Service.java'
                    file: service.java
                    iter: tables
      - name: resources
        files:
          - name: 'mappers'
            files:
              - name: '${it.name.className}Mapper.xml'
                iter: tables
                file: mapper.xml