server:
  port: 80
  servlet:
    context-path:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mappers/**.xml
  type-handlers-package: com.baomidou.mybatisplus.extension.handlers
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
      id-type: auto
    banner: false

spring:
  profiles:
    active: dev
  cache:
    type: redis
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
sa-token:
  token-name: Authorization
  timeout: 2592000
  active-timeout: 2592000
  is-concurrent: true
  is-share: false
  token-style: random-128
  is-log: false
  is-print: false
  token-prefix: